FROM armswdev/pytorch-arm-neoverse:r22.12-torch-1.13.0-openblas
WORKDIR /app

# install opencv dependencies
RUN sudo apt-get update && sudo apt-get install libgl1 libglib2.0-0 -y

COPY requirements_docker.txt requirements.txt
RUN sudo pip install -r requirements.txt

COPY . .
CMD ["sudo", "python", "-u", "./restapi.py", "--port", "5000"]